### PR TITLE
add ability to insert .env.local api key

### PR DESCRIPTION
**Pull request by wesbragagt**
Hey yak folks! I love this tool and just had a thought as I was starting to use it. The prompting for api key every time I would change the port for which I serve the app was getting annoying so given it's a NextJS app I thought I could point the apiKey reads from the store to pull from a NEXT_PUBLIC_ENV variable in the .env.local. 

This PR adds those changes and some guidance in the README.

### CODE REVIEW

**Review by poteat — CHANGES_REQUESTED** [review]
It's important to keep the API key secure due to its private nature, as exposing it could result in unauthorized users incurring charges on your OpenAI account.

Hence, I suggest renaming the environment variable from `NEXT_PUBLIC_OPENAI_API_KEY` to a simpler name such as `OPENAI_KEY`. This would avoid giving the impression that the key is meant to be public, which could potentially confuse users.

**Comment by yakGPT** [comment]
Thanks!

**Comment by bgriffen** [comment]
I get prompted for the API keys every time despite making two variables on my unraid container holding the variable names. NEXT_PUBLIC_OPENAI_API_KEY and NEXT_PUBLIC_11LABS_API_KEY - is there any reason I'm getting prompted every time still?

**Comment by bgriffen** [comment]
Any ideas on this? ^

**Pull request merged**
