### PR TITLE
feat(Nav): Clear chats

### PR DESCRIPTION
**Pull request by paulchiu**
Add the ability to clear chats, similar to clear conversations in ChatGPT.

Intentional difference is that clear is always shown instead of hidden until a chat exists.

|ChatGPT version|PR version|
|---|---|
|image|image|

### CODE REVIEW

**Comment by yakGPT** [comment]
Hey, I like this! There should always be a chat selected, can you add a call to `addChat` to the click handler?

**Comment by paulchiu** [comment]
Hey,

Thanks for the quick review. Umm... I think I already put one in, unless you mean elsewhere?

image

**Comment by yakGPT** [comment]
Ah sorry about that! Could you make it behave closer to how OpenAI's version does where it goes "Confirm Clear Chats" and then if select another chat that "Confirm" disappears, or if you click again it clears them. There's also the issue of the link becoming "active" when clicking 
image

**Comment by paulchiu** [comment]
> Could you make it behave closer to how OpenAI's version does where it goes "Confirm Clear Chats" and then if select another chat that "Confirm" disappears, or if you click again it clears them. 

No worries at all. Updated with commit 55c49dba1262528c8737e909dd1af1c3f8b89e3c.

New behaviour:

https://user-images.githubusercontent.com/3478672/229333107-58200e93-48c5-4bd2-93be-3f036a53d419.mp4


> There's also the issue of the link becoming "active" when clicking

Added `event.preventDefault()` to prevent button focus with commit 34e7479122b5a6514e3b4d6804dffc7329d329e5.

**Comment by yakGPT** [comment]
Nice one! 🙏

**Pull request merged**
