### PR TITLE
Update a little css and add i18n support with Chinese translations

### PR DESCRIPTION
**Pull request by InsideBreeze**
Hi there!

I've submitted a Pull Request that includes some style updates for the project, including the removal of the redundant scrollbar (there are two scrollbars in the right) and some visual enhancements to make it look a little more appealing.
In addition to the style changes, this PR also adds internationalization support(by the library i18next) and includes translations in Chinese.

imo this is a great project with a lot of potential, and I appreciate your effort on it.  This was my  first formal PR, so please bear me if something was wrong

### CODE REVIEW

**Comment by doda** [comment]
Hey @InsideBreeze, these improvements looks great, but no matter what I seem to do in local dev, I cannot get the chinese translations to show. I'm using https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc/related?hl=en-US. Do you have any instructions for how to test the translating functionality?

I'm really impressed by your CSS cleanups, I'm a total CSS noob (tbh I hate it lol) and so these are really appreciated.

**Comment by yakGPT** [comment]
Hey @InsideBreeze, these improvements looks great, but no matter what I seem to do in local dev, I cannot get the chinese translations to show. I'm using https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc/related?hl=en-US. Do you have any instructions for how to test the translating functionality?

I'm really impressed by your CSS cleanups, I'm a total CSS noob (tbh I hate it lol) and so these are really appreciated.

**Comment by InsideBreeze** [comment]
Thank you for your reply! It's strange that when I tested the translation functionality using the addon you provided, it worked fine. Could you please try manually refreshing the page after selecting the zh language option?

I believe that next-i18next will redirect you to the appropriate localized page, for example localhost:3000/zh, when your system language or preferred language in your browser is set to Chinese. Therefore, you can test the redirection functionality by using `curl -H "Accept-Language: zh" http://localhost:3000/`, which should output` /zh`. You can then directly visit `localhost:3000/zh` to test the translations. This process is very inconvenient though.

I'm still getting used to writing CSS. Your reply means a lot for me, I will keep learning from your codes!

**Comment by InsideBreeze** [comment]
> Hey @InsideBreeze, these improvements looks great, but no matter what I seem to do in local dev, I cannot get the chinese translations to show. I'm using https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc/related?hl=en-US. Do you have any instructions for how to test the translating functionality?
> 
> I'm really impressed by your CSS cleanups, I'm a total CSS noob (tbh I hate it lol) and so these are really appreciated.

**Comment by InsideBreeze** [comment]
:) Sorry for closing this pr accidently. :)

**Pull request closed without merging**
